name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Instalar Dependencias (CPU)
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libopenblas-dev liblapack-dev

    - name: Instalar CUDA Toolkit
      uses: Jimver/cuda-toolkit@v0.2.15
      id: cuda-toolkit
      with:
        cuda: '12.5.0'

    - name: Compilar con Make
      run: |
        make clean
        make -j$(nproc)
